- name: install mariadb package (CentOS)
  tags: db,mariadb,centos
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (Debian)
  tags: db,mariadb,debian
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Debian"
